config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#welcome'

  get 'welcome' => 'static_pages#welcome'

  get 'admin' => "admins#show"

  get 'thankyou' => 'carts#thankyou'

  resources :categories

  resources :products

  resources :carts

  resources :histories

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :user
  belongs_to :product

end

app/models/categories_product.rb
class CategoriesProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categories_products
  has_many :products, through: :categories_products
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :categories_products
  has_many :categories, through: :categories_products
  has_many :carts
  has_many :users, through: :carts

  validates :name, length: { minimum: 2 }, presence: true
  validates :description, presence: true, length: { maximum: 2500 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :carts
  has_many :products, through: :carts

  has_many :histories

  before_save {self.email.downcase!}

  validates :username, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length:     { maximum: 150 },
                                    format:     { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
# http_basic_authenticate_with name: "admin", password: "secret"

  def show
    @categories = Category.all
    @products = Product.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to new_session_path unless current_user
  end

  def check_admin
    unless current_user.admin
      flash[:error] = "restricted area"
      redirect_to root_url
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    if request.xhr?
      cart = current_user.carts
      render plain: cart.count
    end
  end

  def new
    @cart = Cart.new
  end

  def show
    @cart = current_user.products
  end

  def create
    @products = current_user.products
    if request.xhr?
      product = Product.find request[:product_id]
      cart_stock = Cart.where(product_id: request[:product_id], user_id: current_user.id ).count
      if cart_stock < product.stock
        Cart.create user_id: current_user.id, product_id: request[:product_id]
        render partial: "cart_products", layout: false, locals: {products: @products}
      else
        render partial: "cart_products", layout: false, locals: {products: @products}
      end
    else
      redirect_to root_path
    end
  end

 def destroy
    @products = current_user.products
    if request.xhr?
      product = Product.find_by name: request[:product_name]
      cart = Cart.find_by user_id: current_user.id, product_id: product.id
      cart.destroy
      render partial: "cart_products", layout: false, locals: {products: @products}
    else
      redirect_to root_path
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_admin, only: [:new, :create]
  def index
    @categories = Category.all
  end

  def show
    category = Category.find(params[:id])
    unless category
      flash[:errors] = "Category not found"
      redirect_to root_url
    else
      @products = category.products
    end
  end

  def new
    @category = Category.new
  end

  def create
    Category.create(cat_params)
    redirect_to admin_path
  end

  private
  def cat_params
    params.require(:category).permit(:name)
  end

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

def index
  @histories = current_user.histories
end

def create
  history = History.new
  current_user.products.each do |product|
    item = Product.find(product.id)
    item.stock -= 1
    item.save
    history.orders << product.id
  end
  history.user_id = current_user.id
  history.save
  current_user.carts.clear
  ExampleMailer.checkout_email(current_user).deliver
  redirect_to thankyou_path
end

def thankyou
  @histories = current_user.histories
end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @category_id = params[:category_id]
    @products = Category.find(params[:category_id]).products.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @categories = Category.all
    @product = Product.new
  end

  def create
    @categories = Category.all
    @product = Product.new(product_params)
    if @product.valid?
      @product.save
      cat_params.each do |_, v|
        @product.categories_products.create(category_id: v.to_i)
      end
      flash[:success] = "Product Created"
      redirect_to admin_path
    else
      flash[:danger] = @product.errors
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
    @all_cats = Category.all
    @category_id = @product.categories.map { |x| x.id }
  end

  def update
    @product = Product.find(params[:id])

    if @product
      @product.update_attributes(product_params)
      @product.categories_products.each { |record| record.destroy }
      cat_params.each do |_, v|
        @product.categories_products.create(category_id: v.to_i)
      end
      redirect_to admin_path
    else
      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to admin_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :stock)
  end

  def cat_params
    all_params = params.require(:product).permit!
    keys = all_params.keys - product_params.keys
    return all_params.select { |k, v| keys.include?(k) }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email(params['session']['email'])
    if user && user.authenticate(params['session']['password'])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash[:error] = "Password or email not found"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def welcome
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(user_params)
    if user.valid?
      user.save
      ExampleMailer.sample_email(user).deliver
      flash[:success] = "User created"
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash[:danger] = user.errors
      render "new"
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_admin?
    current_user.admin
  end

end

app/views/admins/show.html.erb
<div class="jumbotron my-jumbotron">
<h2><%= link_to "Add a category", new_category_path %></h2>
<h2><%= link_to "Add a product", new_product_path %></h2>

  <div class="row">
    <h2>Categories</h2>
      <% @categories.each do |cat| %>
        <p><%= link_to cat.name, category_path(cat.id) %></p>
      <% end %>
</div>

      <% @products.each do |product| %>
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
          <%= image_tag("computer.png", width: '50', height: '50')%>
          <br>
          <span style="color: red; font-size: 20px">
          $<%= product.price %> - Stock: <%= product.stock %>
          </span>
          <h3> Name: <%= truncate(product.name, length: 10)%></h3>
          Description: <%= product.description %>
          <br>
          <div id="product<%=product.id%>" >
          <%= link_to 'Edit', edit_product_path(product)%> | <%= link_to "delete", product_path(product.id), method: :delete %>
          <br><br>
          </div>
        </div>
      <% end %>

         <div class="container">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Product number</th>
                  <th>Name</th>
                  <th>Price</th>
                  <th>Stock</th>
                  <th>Description</th>
                </tr>
              </thead>
                <% @products.each_with_index do |product, index| %>
                <tbody>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= product.name%></td>
                    <td><%= product.price%></td>
                    <td><%= product.stock%></td>
                    <td><%= product.description%></td>

                  </tr>
                </tbody>
                <% end %>
            </table>
          </div>
        </div>

app/views/carts/_cart_products.html.erb
<div style="text-align:center;" class="jumbotron my-jumbotron">
  <% product_holder = Hash.new(0)%>
  <% total_price = []%>
  <%
  products.each do |v|
    product_holder[v.name] += 1
    total_price << v.price
  end
  %>
  <h3> Current Shopping Cart </h3>
  <% product_holder.each do |k,v|%>
    <div class="<%=k%>">
      <%= "#{k} x #{v}"  %><a id="item-del-btn" class="close" style="clear: both;">x</a>
    </div>
  <%end %>
    <% if total_price.empty? %>
      <h4> Shopping Cart empty </h4>
      <h4> Total: $<%="0.00"%> </h4>
    <% else %>
      <h4> Total: $<%= total_price.reduce(:+) %></h4>
    <% end %>
  <br>
</div>

app/views/carts/_cart_remove.html.erb
<div style="text-align:center;" class="jumbotron my-jumbotron">
  <% product_holder = Hash.new(0)%>
  <% total_price = []%>

  <%
  products.each do |v|
    product_holder[v.name] -= 1
    total_price << v.price
  end
  %>
  <h3> Current Shopping Cart </h3>
  <% product_holder.each do |k,v|%>
  <div class="<%=k%>">
    <%= "#{k} x #{v}"  %><a id="item-del-btn" class="close" style="clear: both;">x</a>
    <br>
  </div>
  <%end %>
  <%end %>
    <% if total_price.empty? %>
      <h4> Shopping Cart empty </h4>
      <h4> Total: $<%="0.00"%> </h4>
    <% else %>
      <h4> Total: $<%= total_price.reduce(:+) %></h4>
    <% end %>
  <br>
</div>

app/views/carts/show.html.erb
  <% product_holder = Hash.new(0)%>
  <% total_price = []%>
  <%
  @cart.each do |v|
    product_holder[v.name] += 1
    total_price << v.price
  end
  %>

 <div class="container">
  <h1 class="page-header">Shopping Cart</h1>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Unit Price</th>
          <th>Quantity</th>
        </tr>
      </thead>
        <% product_holder.each do |k,v|%>
        <% prod = Product.find_by name: k %>
        <tbody>
          <tr>
            <td><%= k %></td>
            <td><%= number_to_currency(prod.price) %></td>
            <td><%= "x #{v}"%></td>
          </tr>
        <% end %>
          <td>Total Price: <%= number_to_currency(total_price.reduce(:+)) %></td>
        </tbody>
    </table>
  </div>
</div>

<div class="jumbotron my-jumbotron">
  <%= button_to "Checkout", histories_path, class: "btn btn-lg btn-primary", method: :post %>
</div>

app/views/carts/thankyou.html.erb
<div class="jumbotron my-jumbotron">
  <h1> Thank you for your purchase! </h1>
</div>

app/views/categories/index.html.erb
<div class="jumbotron my-jumbotron">
  <div class="row">
  	<h1 style="text-align:center;">Categories</h1>
  	<br><br>
    <% @categories.each do |info| %>
      <div style="text-align:center;" class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <%= link_to image_tag("lorem.png", class: "img-thumbnail", alt: "image placeholder", data: { src: "holder.js/200x200" }, width: '250', height: '250'), category_path(info.id)%>

        <h2><%= info.name %></h2>
      </div><!--/.col-xs-6.col-lg-4-->
    <% end %>
</div>
</div>

app/views/categories/new.html.erb
<div class="jumbotron my-jumbotron">
<%= form_for @category do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br><br>

  <%= f.submit %>

<% end %>
</div>

app/views/categories/show.html.erb
<div class="jumbotron my-jumbotron">
<% if @products.count > 0 %>
  <div class="shoppingcartshow"></div>
  <h1> Products </h1>
  <div class="row" id="products-list" >
  <br>
    <% @products.each do |pro| %>
      <div style="text-align:center;" class="col-lg-4 col-md-4 col-sm-6 col-xs-12">

        <%= link_to image_tag("computer.png", class: "img-thumbnail", alt: "image placeholder", data: { src: "holder.js/200x200" }, width: '250', height: '250'), product_path(pro.id)%>

        <h2><%= truncate(pro.name, length: 15) %></h2>
        Stock:<p id="stock<%= pro.id.to_s %>" class="product-<%=pro.name.gsub(/\s/, "")%>" ><%= pro.stock %></p>
        <% if current_user %>
          <button id=<%= pro.id.to_s %> class="add-2-kart" type="button">Add to Cart</button>
          <br><br>
        <% end %>
      </div><!--/.col-xs-6.col-lg-4-->
    <% end %>
  </div><!--/row-->
<% end %>
</div>

app/views/histories/index.html.erb
<% if @histories.count == 0%>
<h1 class="page-header">Order History</h1>
<div class="jumbotron my-jumbotron">
  Order History Is Empty.
</div>
<% else %>
<% @histories.each do |info|
@created_at = info.created_at

holder = Hash.new(0)
total_paid = []
  info.orders.each do |product_id|
    product = Product.find(product_id)
    holder[product_id] += 1
    total_paid << product.price

  end
end %>

<div class="container">
  <h1 class="page-header">Order History</h1>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <% @histories.each do |info|
          holder = Hash.new(0)
          total_paid = []
            info.orders.each do |product_id|
              product = Product.find(product_id)
              holder[product_id] += 1
              total_paid << product.price
          %>
          <% end %>
          <th>Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
        </tr>
      </thead>
            <% holder.each do |k,v| %>
            <% item = Product.find(k) %>
        <tbody>
          <tr>
            <td><%= item.name %></td>
            <td><%= number_to_currency(item.price)%></td>
            <td><%= "x #{v}" %></td>
          </tr>
          <% end %>
          <td> Order Purchased at: <%= info.created_at %> </td>
          <td>Order total: <%= number_to_currency(total_paid.reduce(:+)) %></td>
        </tbody>
        <% end %>
    </table>
  </div>
</div>

<% end %>

app/views/layouts/_footer.html.erb
      <footer>
      <br>
        <p>&copy; 2033 Master Ware, Inc.</p>
      </footer>

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Master Ware", root_url, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_url %></li>
            <% if current_user %>
              <%if is_admin? %>
                <li><%= link_to "Admin", admin_path %></li>
                <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
              <% else %>
              <li><%= link_to "Order History", histories_path %> </li>
              <li class="active" id="kart-button" >
                <%= link_to "Shopping Cart (#{current_user.carts.count})", cart_path('~') %>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
              </li>
              <% end %>
            <% else %>
              <li><%= link_to 'Login', new_session_path %></li>
              <li><%= link_to "Sign up", new_user_path %></li>
            <% end %>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shoppe
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      .jumbotron
      = render 'shared/flash_message'
      = yield
      = render 'layouts/footer'

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= form_for :product, url: product_path(@product), method: :put do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <%= f.label :price %>:
  <%= f.number_field :price, :step => 'any' %><br><br>

  <%= f.label :stock %>:
  <%= f.number_field :stock %><br><br>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

<ul>
  <% @all_cats.each do |cat| %>
    <% if @category_id.include?(cat.id) %>
      <li><p><%= check_box_tag "product[#{cat.name}]", "#{cat.id}", true %> <%= cat.name %></p></li>
    <% else %>
      <li><p><%= check_box_tag "product[#{cat.name}]", "#{cat.id}" %> <%= cat.name %></p></li>
    <% end %>
  <% end %>
</ul>


  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/products/index.html.erb
  <div class="row">
    <% @products.each do |info| %>
      <div style="text-align:center;" class="col-lg-3 col-md-4 col-sm-6 col-  xs-12">
        <%= image_tag "computer.png", class: "img-thumbnail", alt: "image placeholder", data: { src: "holder.js/200x200" }, width: '150', height: '150'%>
        <h2><%= info.name %></h2>
        <p><%= info.description %> </p>
        <p style="color: red; font-size: 20px">$<%= info.price %> - Stock: <%= info.stock %> </p>
        <button></button>>

        <p>
        <%= link_to "View details", category_product_path(@category_id, info.id), role: "button", class: "btn btn-default" %>
        </p>
      </div><!--/.col-xs-6.col-lg-4-->
    <% end %>
  </div><!--/row-->

app/views/products/new.html.erb
<!-- <div class="centered"> -->
<%= form_for @product, url: products_path do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br><br>

  <%= f.label :price %>:
  <%= f.number_field :price, :step => 'any' %><br><br>

  <%= f.label :stock %>:
  <%= f.number_field :stock %><br><br>

  <%= f.label :description %>:<br>
  <%= f.text_area :description %>

<br>
<ul>
  <% @categories.each do |cat| %>
    <li><p><%= check_box_tag "product[#{cat.name}]", "#{cat.id}" %> <%= cat.name %></p></li>
  <% end %>
</ul>

<br>
  <%= f.submit %>

<% end %>
<!-- </div> -->

app/views/products/show.html.erb
<div class="jumbotron my-jumbotron">

<%= link_to image_tag("computer.png", class: "img-thumbnail", alt: "image placeholder", data: { src: "holder.js/200x200" }, width: '250', height: '250'), categories_path%>
<br><br>
<p>Name: <%= @product.name %></p>
<p>Price: <%= @product.price %></p>
<p>Stock: <%= @product.stock %></p>
<p>Description: <%= @product.description %></p>
</div>

app/views/shared/_flash_message.html.erb
<% if flash[:success] %>
  <% flash.each do |message_type, msg| %>
    <div class="alert alert-<%= message_type %>">
      <%= msg %>
    </div>
  <% end %>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
      <%= flash[:error] %>
  </div>
<% else %>
  <% flash.each do |message_type, errors| %>
    <div class="alert alert-<%= message_type %>">
    Total <%= pluralize(errors.count, "error") %>:
      <ul>
      <% errors.full_messages.each do |error|%>
        <li><%= error %></li>
      <% end%>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/static_pages/welcome.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("banner1.png") %>
      <div class="carousel-caption">
        <h3></h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag("banner2.png") %>
      <div class="carousel-caption">
        <h3></h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag("banner3.png") %>
      <div class="carousel-caption">
        <h3></h3>
      </div>
    </div>
  </div>




  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div> <!-- Carousel -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">

<script>
  $('.carousel').carousel({
    interval: 3000
  })
</script>

<br><br>

<div class="jumbotron my-jumbotron">
  <h2>Welcome to the future</h2>
  <%= button_to "Browse by category", categories_path, class: "btn btn-lg btn-primary", method: :get %>
</div>

app/views/users/new.html.erb
<style type="text/css">
.container {
    width: 60%;
    clear: both;
}
.container input {
    width: 100%;
    clear: both;
}
</style>

<div class="jumbotron my-jumbotron container">
<h2> Sign Up </h2>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :username %>
  <br>
  Email: <%= f.text_field :email %>
  <br>
  Password: <%= f.password_field :password %>
  <br>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit "Submit" %>

<% end %>
</div>